<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>0.0.7</Version>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Bounteous.Data" Version="0.0.31" />
      <PackageReference Include="EntityFrameworkCore.NamingConventions" Version="8.0.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.9" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    </ItemGroup>

</Project>
